use crate::dependent::resource_locale_fallbacks;

use super::resource_text_override;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum UiTextKey {
    Menu,
    Settings,
    Viewer,
    Plugins,
    Resources,
    Render,
    Window,
    Navigation,
    Filer,
    Background,
    Animation,
    Grayscale,
    MangaMode,
    MangaRightToLeft,
    Locale,
    Fonts,
    FontSize,
    Auto,
    Theme,
    System,
    Light,
    Dark,
    ZoomMode,
    ScaleMode,
    Resize,
    Fullscreen,
    RememberSize,
    RememberPosition,
    RegisterSystem,
    CleanSystem,
    WindowSizeRelative,
    WindowSizeExact,
    UseExactSize,
    UseRelativeSize,
    EndOfFolder,
    ReloadCurrent,
    Close,
    SaveAs,
    Next,
    Previous,
    ToggleSettings,
    ToggleFiler,
    ToggleManga,
    NoDisplayableFileFound,
    OpenDirectoryOrFileFromFiler,
    Save,
    Directory,
    ChooseFolder,
    Format,
    Cancel,
    NotSelected,
    List,
    ThumbnailSmall,
    ThumbnailMedium,
    ThumbnailLarge,
    Detail,
    Sort,
    Name,
    NameSortOrder,
    Date,
    Size,
    Asc,
    Desc,
    Separate,
    Os,
    Case,
    NoCase,
    Filter,
    Extension,
    Url,
    OpenUrl,
    Up,
    Loading,
    Subfiler,
    RightToLeft,
    LeftToRight,
    FolderArchive,
    Black,
    Gray,
    Tile,
    NameLabel,
    Separator,
    SeparatorStyle,
    SeparatorColor,
    SeparatorPixels,
    None,
    Solid,
    Shadow,
    RememberSavePath,
    Help,
    Apply,
    Undo,
    Reset,
    Enable,
    SearchPath,
    Browse,
    LoadModules,
    Modules,
    SearchPathOsApi,
    FitWidth,
    FitHeight,
    FitScreen,
    FitScreenIncludeSmaller,
    FitScreenOnlySmaller,
    Nearest,
    Bilinear,
    Bicubic,
    Lanczos3,
    FastGpu,
    PreciseCpu,
    Stop,
    Loop,
    Recursive,
    RegisteredFileAssociations,
    FailedFileAssociations,
    CleanedSystemIntegration,
    Workaround,
    Archive,
    ThresholdMb,
    LocalCache,
    ThumbnailSuppression,
    RestartRecommended,
    RestartToApplyPluginChanges,
    PaneSide,
    Left,
    Right,
    ProgramName,
    Version,
    Author,
    Copyright,
}

pub(crate) fn tr(locale: &str, key: UiTextKey) -> &'static str {
    let key_name = format!("{key:?}");
    for candidate in resource_locale_fallbacks(locale) {
        if let Some(value) = resource_text_override(&candidate, &key_name) {
            return value;
        }
        match candidate.as_str() {
            "ja_JP" | "ja" => return ja(key),
            "en_US" | "en_GB" | "en" => return en(key),
            _ => {}
        }
    }
    en(key)
}

fn en(key: UiTextKey) -> &'static str {
    match key {
        UiTextKey::Menu => "Menu",
        UiTextKey::Settings => "Settings",
        UiTextKey::Viewer => "Viewer",
        UiTextKey::Plugins => "Plugins",
        UiTextKey::Resources => "Resources",
        UiTextKey::Render => "Render",
        UiTextKey::Window => "Window",
        UiTextKey::Navigation => "Navigation",
        UiTextKey::Filer => "Filer",
        UiTextKey::Background => "Background",
        UiTextKey::Animation => "Animation",
        UiTextKey::Grayscale => "Grayscale",
        UiTextKey::MangaMode => "Manga mode",
        UiTextKey::MangaRightToLeft => "Manga right-to-left",
        UiTextKey::Locale => "Locale",
        UiTextKey::Fonts => "Fonts",
        UiTextKey::FontSize => "Font size",
        UiTextKey::Auto => "Auto",
        UiTextKey::Theme => "Theme",
        UiTextKey::System => "System",
        UiTextKey::Light => "Light",
        UiTextKey::Dark => "Dark",
        UiTextKey::ZoomMode => "Zoom mode",
        UiTextKey::ScaleMode => "Scale mode",
        UiTextKey::Resize => "Resize",
        UiTextKey::Fullscreen => "Fullscreen",
        UiTextKey::RememberSize => "Remember size",
        UiTextKey::RememberPosition => "Remember position",
        UiTextKey::RegisterSystem => "Register extensions",
        UiTextKey::CleanSystem => "Clean system integration",
        UiTextKey::WindowSizeRelative => "Window size: relative",
        UiTextKey::WindowSizeExact => "Window size: exact",
        UiTextKey::UseExactSize => "Use exact size",
        UiTextKey::UseRelativeSize => "Use relative size",
        UiTextKey::EndOfFolder => "End of folder",
        UiTextKey::ReloadCurrent => "Reload current",
        UiTextKey::Close => "Close",
        UiTextKey::SaveAs => "Save As",
        UiTextKey::Next => "Next",
        UiTextKey::Previous => "Previous",
        UiTextKey::ToggleSettings => "Toggle Settings",
        UiTextKey::ToggleFiler => "Toggle Filer",
        UiTextKey::ToggleManga => "Toggle Manga",
        UiTextKey::NoDisplayableFileFound => "No displayable file found.",
        UiTextKey::OpenDirectoryOrFileFromFiler => "Open a directory or file from the filer.",
        UiTextKey::Save => "Save",
        UiTextKey::Directory => "Directory",
        UiTextKey::ChooseFolder => "Choose folder",
        UiTextKey::Format => "Format",
        UiTextKey::Cancel => "Cancel",
        UiTextKey::NotSelected => "(not selected)",
        UiTextKey::List => "List",
        UiTextKey::ThumbnailSmall => "Thumb S",
        UiTextKey::ThumbnailMedium => "Thumb M",
        UiTextKey::ThumbnailLarge => "Thumb L",
        UiTextKey::Detail => "Detail",
        UiTextKey::Sort => "Sort",
        UiTextKey::Name => "Name",
        UiTextKey::NameSortOrder => "Name sort order",
        UiTextKey::Date => "Date",
        UiTextKey::Size => "Size",
        UiTextKey::Asc => "Asc",
        UiTextKey::Desc => "Desc",
        UiTextKey::Separate => "Separate folders",
        UiTextKey::Os => "OS Like",
        UiTextKey::Case => "Case-sensitive",
        UiTextKey::NoCase => "Case-insensitive",
        UiTextKey::Filter => "Filter",
        UiTextKey::Extension => "Ext",
        UiTextKey::Url => "URL",
        UiTextKey::OpenUrl => "Open URL",
        UiTextKey::Up => "..",
        UiTextKey::Loading => "Loading...",
        UiTextKey::Subfiler => "Subfiler",
        UiTextKey::RightToLeft => "R2L",
        UiTextKey::LeftToRight => "L2R",
        UiTextKey::FolderArchive => "Folder / Archive",
        UiTextKey::Black => "Black",
        UiTextKey::Gray => "Gray",
        UiTextKey::Tile => "Tile",
        UiTextKey::NameLabel => "Name",
        UiTextKey::Separator => "Separator",
        UiTextKey::SeparatorStyle => "Style",
        UiTextKey::SeparatorColor => "Color",
        UiTextKey::SeparatorPixels => "Pixels",
        UiTextKey::None => "None",
        UiTextKey::Solid => "Solid",
        UiTextKey::Shadow => "Shadow",
        UiTextKey::RememberSavePath => "Remember image save folder",
        UiTextKey::Help => "Help",
        UiTextKey::Apply => "Apply",
        UiTextKey::Undo => "Undo",
        UiTextKey::Reset => "Reset",
        UiTextKey::Enable => "Enable",
        UiTextKey::SearchPath => "Search path",
        UiTextKey::Browse => "Browse...",
        UiTextKey::LoadModules => "Load modules",
        UiTextKey::Modules => "Modules",
        UiTextKey::SearchPathOsApi => "Search path: OS API",
        UiTextKey::FitWidth => "FitWidth",
        UiTextKey::FitHeight => "FitHeight",
        UiTextKey::FitScreen => "FitScreen",
        UiTextKey::FitScreenIncludeSmaller => "FitScreenIncludeSmaller",
        UiTextKey::FitScreenOnlySmaller => "FitScreenOnlySmaller",
        UiTextKey::Nearest => "Nearest",
        UiTextKey::Bilinear => "Bilinear",
        UiTextKey::Bicubic => "Bicubic",
        UiTextKey::Lanczos3 => "Lanczos3",
        UiTextKey::FastGpu => "Fast (GPU)",
        UiTextKey::PreciseCpu => "Precise (CPU)",
        UiTextKey::Stop => "STOP",
        UiTextKey::Loop => "LOOP",
        UiTextKey::Recursive => "RECURSIVE",
        UiTextKey::RegisteredFileAssociations => "Registered file associations",
        UiTextKey::FailedFileAssociations => "Failed to register file associations",
        UiTextKey::CleanedSystemIntegration => "Cleaned system integration",
        UiTextKey::Workaround => "Workaround",
        UiTextKey::Archive => "Archive",
        UiTextKey::ThresholdMb => "Threshold (MB)",
        UiTextKey::LocalCache => "Local cache",
        UiTextKey::ThumbnailSuppression => "Suppress heavy thumbnails",
        UiTextKey::RestartRecommended => "Restart recommended",
        UiTextKey::RestartToApplyPluginChanges => {
            "Restart the app to fully reload plugin settings."
        }
        UiTextKey::PaneSide => "Pane side",
        UiTextKey::Left => "Left",
        UiTextKey::Right => "Right",
        UiTextKey::ProgramName => "Program",
        UiTextKey::Version => "Version",
        UiTextKey::Author => "Author",
        UiTextKey::Copyright => "Copyright",
    }
}

fn ja(key: UiTextKey) -> &'static str {
    match key {
        UiTextKey::Menu => "メニュー",
        UiTextKey::Settings => "設定",
        UiTextKey::Viewer => "ビューアー",
        UiTextKey::Plugins => "プラグイン",
        UiTextKey::Resources => "リソース",
        UiTextKey::Render => "描画",
        UiTextKey::Window => "ウィンドウ",
        UiTextKey::Navigation => "ナビゲーション",
        UiTextKey::Filer => "ファイラー",
        UiTextKey::Background => "背景",
        UiTextKey::Animation => "アニメーション",
        UiTextKey::Grayscale => "グレースケール",
        UiTextKey::MangaMode => "マンガモード",
        UiTextKey::MangaRightToLeft => "マンガ右綴じ",
        UiTextKey::Locale => "ロケール",
        UiTextKey::Fonts => "フォント",
        UiTextKey::FontSize => "フォントサイズ",
        UiTextKey::Auto => "自動",
        UiTextKey::Theme => "テーマ",
        UiTextKey::System => "システム",
        UiTextKey::Light => "ライト",
        UiTextKey::Dark => "ダーク",
        UiTextKey::ZoomMode => "ズームモード",
        UiTextKey::ScaleMode => "拡大縮小",
        UiTextKey::Resize => "リサイズ",
        UiTextKey::Fullscreen => "フルスクリーン",
        UiTextKey::RememberSize => "サイズを記憶",
        UiTextKey::RememberPosition => "位置を記憶",
        UiTextKey::RegisterSystem => "拡張子を登録",
        UiTextKey::CleanSystem => "システム登録を削除",
        UiTextKey::WindowSizeRelative => "ウィンドウサイズ: 相対",
        UiTextKey::WindowSizeExact => "ウィンドウサイズ: 固定",
        UiTextKey::UseExactSize => "固定サイズを使う",
        UiTextKey::UseRelativeSize => "相対サイズを使う",
        UiTextKey::EndOfFolder => "フォルダ終端",
        UiTextKey::ReloadCurrent => "現在を再読込",
        UiTextKey::Close => "閉じる",
        UiTextKey::SaveAs => "保存形式",
        UiTextKey::Next => "次へ",
        UiTextKey::Previous => "前へ",
        UiTextKey::ToggleSettings => "設定を切替",
        UiTextKey::ToggleFiler => "ファイラーを切替",
        UiTextKey::ToggleManga => "マンガを切替",
        UiTextKey::NoDisplayableFileFound => "表示できるファイルがありません。",
        UiTextKey::OpenDirectoryOrFileFromFiler => {
            "ファイラーからディレクトリまたはファイルを開いてください。"
        }
        UiTextKey::Save => "保存",
        UiTextKey::Directory => "フォルダ",
        UiTextKey::ChooseFolder => "フォルダを選択",
        UiTextKey::Format => "形式",
        UiTextKey::Cancel => "キャンセル",
        UiTextKey::NotSelected => "未選択",
        UiTextKey::List => "一覧",
        UiTextKey::ThumbnailSmall => "サムネ小",
        UiTextKey::ThumbnailMedium => "サムネ中",
        UiTextKey::ThumbnailLarge => "サムネ大",
        UiTextKey::Detail => "詳細",
        UiTextKey::Sort => "ソート",
        UiTextKey::Name => "名前",
        UiTextKey::NameSortOrder => "名前のソート順",
        UiTextKey::Date => "更新日時",
        UiTextKey::Size => "サイズ",
        UiTextKey::Asc => "昇順",
        UiTextKey::Desc => "降順",
        UiTextKey::Separate => "フォルダ分離表示",
        UiTextKey::Os => "OS準拠",
        UiTextKey::Case => "Aa区別",
        UiTextKey::NoCase => "Aa無視",
        UiTextKey::Filter => "フィルタ",
        UiTextKey::Extension => "拡張子",
        UiTextKey::Url => "URL",
        UiTextKey::OpenUrl => "URLを開く",
        UiTextKey::Up => "..",
        UiTextKey::Loading => "読み込み中...",
        UiTextKey::Subfiler => "サブファイラー",
        UiTextKey::RightToLeft => "右綴じ",
        UiTextKey::LeftToRight => "左綴じ",
        UiTextKey::FolderArchive => "フォルダ / アーカイブ",
        UiTextKey::Black => "黒",
        UiTextKey::Gray => "グレー",
        UiTextKey::Tile => "タイル",
        UiTextKey::NameLabel => "名前",
        UiTextKey::Separator => "セパレーター",
        UiTextKey::SeparatorStyle => "種類",
        UiTextKey::SeparatorColor => "色",
        UiTextKey::SeparatorPixels => "幅",
        UiTextKey::None => "なし",
        UiTextKey::Solid => "単色",
        UiTextKey::Shadow => "影",
        UiTextKey::RememberSavePath => "画像保存先を記憶",
        UiTextKey::Help => "ヘルプ",
        UiTextKey::Apply => "適用",
        UiTextKey::Undo => "元に戻す",
        UiTextKey::Reset => "初期化",
        UiTextKey::Enable => "有効",
        UiTextKey::SearchPath => "検索パス",
        UiTextKey::Browse => "参照...",
        UiTextKey::LoadModules => "モジュールを読み込む",
        UiTextKey::Modules => "モジュール数",
        UiTextKey::SearchPathOsApi => "検索パス: OS API",
        UiTextKey::FitWidth => "幅に合わせる",
        UiTextKey::FitHeight => "高さに合わせる",
        UiTextKey::FitScreen => "画面に合わせる",
        UiTextKey::FitScreenIncludeSmaller => "画面に合わせる（小さい画像も拡大）",
        UiTextKey::FitScreenOnlySmaller => "小さい画像だけ画面に合わせる",
        UiTextKey::Nearest => "ニアレスト",
        UiTextKey::Bilinear => "バイリニア",
        UiTextKey::Bicubic => "バイキュービック",
        UiTextKey::Lanczos3 => "Lanczos3",
        UiTextKey::FastGpu => "高速(GPU)",
        UiTextKey::PreciseCpu => "精密(CPU)",
        UiTextKey::Stop => "停止",
        UiTextKey::Loop => "ループ",
        UiTextKey::Recursive => "再帰",
        UiTextKey::RegisteredFileAssociations => "拡張子を登録しました",
        UiTextKey::FailedFileAssociations => "拡張子の登録に失敗しました",
        UiTextKey::CleanedSystemIntegration => "システム登録を削除しました",
        UiTextKey::Workaround => "ワークアラウンド",
        UiTextKey::Archive => "アーカイブ",
        UiTextKey::ThresholdMb => "閾値 (MB)",
        UiTextKey::LocalCache => "ローカルキャッシュ",
        UiTextKey::ThumbnailSuppression => "重いサムネイルを抑制",
        UiTextKey::RestartRecommended => "再起動を推奨",
        UiTextKey::RestartToApplyPluginChanges => {
            "プラグイン設定を完全に反映するにはアプリの再起動が必要です。"
        }
        UiTextKey::PaneSide => "ペイン位置",
        UiTextKey::Left => "左",
        UiTextKey::Right => "右",
        UiTextKey::ProgramName => "プログラム名",
        UiTextKey::Version => "バージョン",
        UiTextKey::Author => "作者",
        UiTextKey::Copyright => "著作権",
    }
}
