use crate::dependent::resource_locale_fallbacks;

use super::resource_text_override;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum UiTextKey {
    Menu,
    Settings,
    Viewer,
    Input,
    Plugins,
    Resources,
    Render,
    Window,
    Navigation,
    Filer,
    Background,
    Animation,
    Grayscale,
    MangaMode,
    MangaRightToLeft,
    Locale,
    Fonts,
    FontSize,
    Auto,
    Theme,
    System,
    Light,
    Dark,
    ZoomMode,
    ScaleMode,
    Resize,
    Fullscreen,
    RememberSize,
    RememberPosition,
    RegisterSystem,
    CleanSystem,
    WindowSizeRelative,
    WindowSizeExact,
    UseExactSize,
    UseRelativeSize,
    EndOfFolder,
    ReloadCurrent,
    Close,
    SaveAs,
    Next,
    ToggleSettings,
    ToggleFiler,
    ToggleManga,
    NoDisplayableFileFound,
    OpenDirectoryOrFileFromFiler,
    Save,
    Directory,
    ChooseFolder,
    Format,
    Cancel,
    NotSelected,
    List,
    ThumbnailSmall,
    ThumbnailMedium,
    ThumbnailLarge,
    Detail,
    Sort,
    Name,
    NameSortOrder,
    Date,
    Size,
    Asc,
    Desc,
    Separate,
    Os,
    Case,
    NoCase,
    Filter,
    Extension,
    Url,
    OpenUrl,
    Up,
    Loading,
    Subfiler,
    RightToLeft,
    LeftToRight,
    FolderArchive,
    Black,
    Gray,
    Tile,
    NameLabel,
    Separator,
    SeparatorStyle,
    SeparatorColor,
    SeparatorPixels,
    None,
    Solid,
    Shadow,
    RememberSavePath,
    Help,
    Apply,
    Undo,
    Reset,
    Enable,
    SearchPath,
    Browse,
    LoadModules,
    Modules,
    SearchPathOsApi,
    FitWidth,
    FitHeight,
    FitScreen,
    FitScreenIncludeSmaller,
    FitScreenOnlySmaller,
    Nearest,
    Bilinear,
    Bicubic,
    Lanczos3,
    FastGpu,
    PreciseCpu,
    Stop,
    Loop,
    Recursive,
    RegisteredFileAssociations,
    FailedFileAssociations,
    CleanedSystemIntegration,
    Workaround,
    Archive,
    ThresholdMb,
    LocalCache,
    ThumbnailSuppression,
    RestartRecommended,
    RestartToApplyPluginChanges,
    PaneSide,
    Left,
    Right,
    ProgramName,
    Version,
    Author,
    Copyright,
    ReplaceDefaultKeyBindings,
    InputBeginnerModeHelp,
    InputKeyboardOnlyNotice,
    AddBinding,
    LoadCurrentCustomBindings,
    ResetToDefaultBindings,
    FunctionLabel,
    KeyCaptureLabel,
    PressKeyToAssign,
    CustomBindingsCount,
    DuplicateBindingWarning,
    Remove,
    CtrlLabel,
    ShiftLabel,
    AltLabel,
    MenuFileSection,
    MenuImageSection,
    MenuViewSection,
    MenuInfoSection,
    MenuAboutSection,
    MoveItem,
    CopyItem,
    DeleteItem,
    RenameItem,
    ImageInformation,
    ZoomInAction,
    ZoomOutAction,
    ZoomResetAction,
    ZoomToggleAction,
    ZoomPresetAction,
    OriginalSizeAction,
    ReloadAction,
    NextImageAction,
    PreviousImageAction,
    FirstImageAction,
    LastImageAction,
    ToggleAnimationAction,
    ToggleGrayscaleAction,
    ToggleSubfilerAction,
    MoveFileAction,
    CopyFileAction,
    DeleteFileAction,
    RenameFileAction,
    SetMoveFolder1Action,
    SetMoveFolder2Action,
    SetCopyFolder1Action,
    SetCopyFolder2Action,
    ReservedKeyWarning,
    FileActionTarget,
    DeleteWithTrashWarning,
    DeleteConfirmQuestion,
    RenameExtensionFixed,
    UnsupportedFilesystemAction,
    FileActionDefaults,
    MoveDestinationFolders,
    MoveFolder1,
    MoveFolder2,
    UseAsMove,
    ActiveMoveFolder,
    CopyDestinationFolders,
    CopyFolder1,
    CopyFolder2,
    UseAsCopy,
    ActiveCopyFolder,
    Folder1,
    Folder2,
    AlertTitle,
    DestinationPathEmpty,
    RenameTargetEmpty,
    CurrentTargetNotEditableFile,
    RenderWorkerDisconnected,
}

pub(crate) fn tr(locale: &str, key: UiTextKey) -> &'static str {
    let key_name = format!("{key:?}");
    for candidate in resource_locale_fallbacks(locale) {
        if let Some(value) = resource_text_override(&candidate, &key_name) {
            return value;
        }
    }
    for candidate in resource_locale_fallbacks(locale) {
        match candidate.as_str() {
            "ja_JP" | "ja" => return ja(key),
            "en_US" | "en_GB" | "en" => return en(key),
            _ => {}
        }
    }
    en(key)
}

fn en(key: UiTextKey) -> &'static str {
    match key {
        UiTextKey::Menu => "Menu",
        UiTextKey::Settings => "Settings",
        UiTextKey::Viewer => "Viewer",
        UiTextKey::Input => "Input",
        UiTextKey::Plugins => "Plugins",
        UiTextKey::Resources => "Resources",
        UiTextKey::Render => "Render",
        UiTextKey::Window => "Window",
        UiTextKey::Navigation => "Navigation",
        UiTextKey::Filer => "Filer",
        UiTextKey::Background => "Background",
        UiTextKey::Animation => "Animation",
        UiTextKey::Grayscale => "Grayscale",
        UiTextKey::MangaMode => "Manga mode",
        UiTextKey::MangaRightToLeft => "Manga right-to-left",
        UiTextKey::Locale => "Locale",
        UiTextKey::Fonts => "Fonts",
        UiTextKey::FontSize => "Font size",
        UiTextKey::Auto => "Auto",
        UiTextKey::Theme => "Theme",
        UiTextKey::System => "System",
        UiTextKey::Light => "Light",
        UiTextKey::Dark => "Dark",
        UiTextKey::ZoomMode => "Zoom mode",
        UiTextKey::ScaleMode => "Scale mode",
        UiTextKey::Resize => "Resize",
        UiTextKey::Fullscreen => "Fullscreen",
        UiTextKey::RememberSize => "Remember size",
        UiTextKey::RememberPosition => "Remember position",
        UiTextKey::RegisterSystem => "Register extensions",
        UiTextKey::CleanSystem => "Clean system integration",
        UiTextKey::WindowSizeRelative => "Window size: relative",
        UiTextKey::WindowSizeExact => "Window size: exact",
        UiTextKey::UseExactSize => "Use exact size",
        UiTextKey::UseRelativeSize => "Use relative size",
        UiTextKey::EndOfFolder => "End of folder",
        UiTextKey::ReloadCurrent => "Reload current",
        UiTextKey::Close => "Close",
        UiTextKey::SaveAs => "Save As",
        UiTextKey::Next => "Next",
        UiTextKey::ToggleSettings => "Toggle Settings",
        UiTextKey::ToggleFiler => "Toggle Filer",
        UiTextKey::ToggleManga => "Toggle Manga",
        UiTextKey::NoDisplayableFileFound => "No displayable file found.",
        UiTextKey::OpenDirectoryOrFileFromFiler => "Open a directory or file from the filer.",
        UiTextKey::Save => "Save",
        UiTextKey::Directory => "Directory",
        UiTextKey::ChooseFolder => "Choose folder",
        UiTextKey::Format => "Format",
        UiTextKey::Cancel => "Cancel",
        UiTextKey::NotSelected => "(not selected)",
        UiTextKey::List => "List",
        UiTextKey::ThumbnailSmall => "Thumb S",
        UiTextKey::ThumbnailMedium => "Thumb M",
        UiTextKey::ThumbnailLarge => "Thumb L",
        UiTextKey::Detail => "Detail",
        UiTextKey::Sort => "Sort",
        UiTextKey::Name => "Name",
        UiTextKey::NameSortOrder => "Name sort order",
        UiTextKey::Date => "Date",
        UiTextKey::Size => "Size",
        UiTextKey::Asc => "Asc",
        UiTextKey::Desc => "Desc",
        UiTextKey::Separate => "Separate folders",
        UiTextKey::Os => "OS Like",
        UiTextKey::Case => "Case-sensitive",
        UiTextKey::NoCase => "Case-insensitive",
        UiTextKey::Filter => "Filter",
        UiTextKey::Extension => "Ext",
        UiTextKey::Url => "URL",
        UiTextKey::OpenUrl => "Open URL",
        UiTextKey::Up => "..",
        UiTextKey::Loading => "Loading...",
        UiTextKey::Subfiler => "Subfiler",
        UiTextKey::RightToLeft => "R2L",
        UiTextKey::LeftToRight => "L2R",
        UiTextKey::FolderArchive => "Folder / Archive",
        UiTextKey::Black => "Black",
        UiTextKey::Gray => "Gray",
        UiTextKey::Tile => "Tile",
        UiTextKey::NameLabel => "Name",
        UiTextKey::Separator => "Separator",
        UiTextKey::SeparatorStyle => "Style",
        UiTextKey::SeparatorColor => "Color",
        UiTextKey::SeparatorPixels => "Pixels",
        UiTextKey::None => "None",
        UiTextKey::Solid => "Solid",
        UiTextKey::Shadow => "Shadow",
        UiTextKey::RememberSavePath => "Remember image save folder",
        UiTextKey::Help => "Help",
        UiTextKey::Apply => "Apply",
        UiTextKey::Undo => "Undo",
        UiTextKey::Reset => "Reset",
        UiTextKey::Enable => "Enable",
        UiTextKey::SearchPath => "Search path",
        UiTextKey::Browse => "Browse...",
        UiTextKey::LoadModules => "Load modules",
        UiTextKey::Modules => "Modules",
        UiTextKey::SearchPathOsApi => "Search path: OS API",
        UiTextKey::FitWidth => "FitWidth",
        UiTextKey::FitHeight => "FitHeight",
        UiTextKey::FitScreen => "FitScreen",
        UiTextKey::FitScreenIncludeSmaller => "FitScreenIncludeSmaller",
        UiTextKey::FitScreenOnlySmaller => "FitScreenOnlySmaller",
        UiTextKey::Nearest => "Nearest",
        UiTextKey::Bilinear => "Bilinear",
        UiTextKey::Bicubic => "Bicubic",
        UiTextKey::Lanczos3 => "Lanczos3",
        UiTextKey::FastGpu => "Fast (GPU)",
        UiTextKey::PreciseCpu => "Precise (CPU)",
        UiTextKey::Stop => "STOP",
        UiTextKey::Loop => "LOOP",
        UiTextKey::Recursive => "RECURSIVE",
        UiTextKey::RegisteredFileAssociations => "Registered file associations",
        UiTextKey::FailedFileAssociations => "Failed to register file associations",
        UiTextKey::CleanedSystemIntegration => "Cleaned system integration",
        UiTextKey::Workaround => "Workaround",
        UiTextKey::Archive => "Archive",
        UiTextKey::ThresholdMb => "Threshold (MB)",
        UiTextKey::LocalCache => "Local cache",
        UiTextKey::ThumbnailSuppression => "Suppress heavy thumbnails",
        UiTextKey::RestartRecommended => "Restart recommended",
        UiTextKey::RestartToApplyPluginChanges => {
            "Restart the app to fully reload plugin settings."
        }
        UiTextKey::PaneSide => "Pane side",
        UiTextKey::Left => "Left",
        UiTextKey::Right => "Right",
        UiTextKey::ProgramName => "Program",
        UiTextKey::Version => "Version",
        UiTextKey::Author => "Author",
        UiTextKey::Copyright => "Copyright",
        UiTextKey::ReplaceDefaultKeyBindings => "Replace default key bindings",
        UiTextKey::InputBeginnerModeHelp => "Beginner mode: edit one binding per row.",
        UiTextKey::InputKeyboardOnlyNotice => {
            "Keyboard and mouse remap are available now. Tablet remap is planned."
        }
        UiTextKey::AddBinding => "Add binding",
        UiTextKey::LoadCurrentCustomBindings => "Load active bindings",
        UiTextKey::ResetToDefaultBindings => "Reset to defaults",
        UiTextKey::FunctionLabel => "Function",
        UiTextKey::KeyCaptureLabel => "Key",
        UiTextKey::PressKeyToAssign => "Click the key box, then press key or mouse input",
        UiTextKey::CustomBindingsCount => "Bindings count",
        UiTextKey::DuplicateBindingWarning => {
            "Duplicate bindings were merged. Last row wins for the same key and modifiers."
        }
        UiTextKey::Remove => "Remove",
        UiTextKey::CtrlLabel => {
            if cfg!(target_os = "macos") {
                "COMMAND"
            } else {
                "CTRL"
            }
        }
        UiTextKey::ShiftLabel => "SHIFT",
        UiTextKey::AltLabel => {
            if cfg!(target_os = "macos") {
                "OPTION"
            } else {
                "ALT"
            }
        }
        UiTextKey::MenuFileSection => "File",
        UiTextKey::MenuImageSection => "Save Image",
        UiTextKey::MenuViewSection => "View",
        UiTextKey::MenuInfoSection => "Information",
        UiTextKey::MenuAboutSection => "About",
        UiTextKey::MoveItem => "Move",
        UiTextKey::CopyItem => "Copy",
        UiTextKey::DeleteItem => "Delete",
        UiTextKey::RenameItem => "Rename",
        UiTextKey::ImageInformation => "Image Information",
        UiTextKey::ZoomInAction => "Zoom In",
        UiTextKey::ZoomOutAction => "Zoom Out",
        UiTextKey::ZoomResetAction => "Zoom Reset",
        UiTextKey::ZoomToggleAction => "Toggle Fit/Original",
        UiTextKey::ZoomPresetAction => "Set Zoom",
        UiTextKey::OriginalSizeAction => "Original Size",
        UiTextKey::ReloadAction => "Reload Current",
        UiTextKey::NextImageAction => "Next Image",
        UiTextKey::PreviousImageAction => "Previous Image",
        UiTextKey::FirstImageAction => "First Image",
        UiTextKey::LastImageAction => "Last Image",
        UiTextKey::ToggleAnimationAction => "Toggle Animation",
        UiTextKey::ToggleGrayscaleAction => "Toggle Grayscale",
        UiTextKey::ToggleSubfilerAction => "Toggle Subfiler",
        UiTextKey::MoveFileAction => "Move File",
        UiTextKey::CopyFileAction => "Copy File",
        UiTextKey::DeleteFileAction => "Delete File",
        UiTextKey::RenameFileAction => "Rename File",
        UiTextKey::SetMoveFolder1Action => "Use Move Folder1",
        UiTextKey::SetMoveFolder2Action => "Use Move Folder2",
        UiTextKey::SetCopyFolder1Action => "Use Copy Folder1",
        UiTextKey::SetCopyFolder2Action => "Use Copy Folder2",
        UiTextKey::ReservedKeyWarning => "Reserved (cannot be changed)",
        UiTextKey::FileActionTarget => "Target",
        UiTextKey::DeleteWithTrashWarning => {
            "Move to trash if possible. If trash move fails, delete permanently."
        }
        UiTextKey::DeleteConfirmQuestion => "Are you sure?",
        UiTextKey::RenameExtensionFixed => "Extension is fixed and cannot be changed.",
        UiTextKey::UnsupportedFilesystemAction => "Unsupported filesystem action",
        UiTextKey::FileActionDefaults => "File Action Defaults",
        UiTextKey::MoveDestinationFolders => "Move destination folders (Folder1 / Folder2)",
        UiTextKey::MoveFolder1 => "Move Folder1",
        UiTextKey::MoveFolder2 => "Move Folder2",
        UiTextKey::UseAsMove => "Use as Move",
        UiTextKey::ActiveMoveFolder => "Active Move Folder",
        UiTextKey::CopyDestinationFolders => "Copy destination folders (Folder1 / Folder2)",
        UiTextKey::CopyFolder1 => "Copy Folder1",
        UiTextKey::CopyFolder2 => "Copy Folder2",
        UiTextKey::UseAsCopy => "Use as Copy",
        UiTextKey::ActiveCopyFolder => "Active Copy Folder",
        UiTextKey::Folder1 => "Folder1",
        UiTextKey::Folder2 => "Folder2",
        UiTextKey::AlertTitle => "Alert",
        UiTextKey::DestinationPathEmpty => "Destination path is empty",
        UiTextKey::RenameTargetEmpty => "Rename target is empty",
        UiTextKey::CurrentTargetNotEditableFile => "Current target is not editable file",
        UiTextKey::RenderWorkerDisconnected => "Render worker disconnected",
    }
}

fn ja(key: UiTextKey) -> &'static str {
    match key {
        UiTextKey::Menu => "メニュー",
        UiTextKey::Settings => "設定",
        UiTextKey::Viewer => "ビューアー",
        UiTextKey::Input => "入力",
        UiTextKey::Plugins => "プラグイン",
        UiTextKey::Resources => "リソース",
        UiTextKey::Render => "描画",
        UiTextKey::Window => "ウィンドウ",
        UiTextKey::Navigation => "ナビゲーション",
        UiTextKey::Filer => "ファイラー",
        UiTextKey::Background => "背景",
        UiTextKey::Animation => "アニメーション",
        UiTextKey::Grayscale => "グレースケール",
        UiTextKey::MangaMode => "マンガモード",
        UiTextKey::MangaRightToLeft => "マンガ右綴じ",
        UiTextKey::Locale => "ロケール",
        UiTextKey::Fonts => "フォント",
        UiTextKey::FontSize => "フォントサイズ",
        UiTextKey::Auto => "自動",
        UiTextKey::Theme => "テーマ",
        UiTextKey::System => "システム",
        UiTextKey::Light => "ライト",
        UiTextKey::Dark => "ダーク",
        UiTextKey::ZoomMode => "ズームモード",
        UiTextKey::ScaleMode => "拡大縮小",
        UiTextKey::Resize => "リサイズ",
        UiTextKey::Fullscreen => "フルスクリーン",
        UiTextKey::RememberSize => "サイズを記憶",
        UiTextKey::RememberPosition => "位置を記憶",
        UiTextKey::RegisterSystem => "拡張子を登録",
        UiTextKey::CleanSystem => "システム登録を削除",
        UiTextKey::WindowSizeRelative => "ウィンドウサイズ: 相対",
        UiTextKey::WindowSizeExact => "ウィンドウサイズ: 固定",
        UiTextKey::UseExactSize => "固定サイズを使う",
        UiTextKey::UseRelativeSize => "相対サイズを使う",
        UiTextKey::EndOfFolder => "フォルダの終わり",
        UiTextKey::ReloadCurrent => "カレントを再読込",
        UiTextKey::Close => "閉じる",
        UiTextKey::SaveAs => "保存形式",
        UiTextKey::Next => "次へ",
        UiTextKey::ToggleSettings => "設定を切替",
        UiTextKey::ToggleFiler => "ファイラーの切替",
        UiTextKey::ToggleManga => "マンガモードの切替",
        UiTextKey::NoDisplayableFileFound => "表示できるファイルがありません。",
        UiTextKey::OpenDirectoryOrFileFromFiler => {
            "ファイラーからディレクトリまたはファイルを開いてください。"
        }
        UiTextKey::Save => "保存",
        UiTextKey::Directory => "フォルダ",
        UiTextKey::ChooseFolder => "フォルダを選択",
        UiTextKey::Format => "形式",
        UiTextKey::Cancel => "キャンセル",
        UiTextKey::NotSelected => "未選択",
        UiTextKey::List => "一覧",
        UiTextKey::ThumbnailSmall => "サムネ小",
        UiTextKey::ThumbnailMedium => "サムネ中",
        UiTextKey::ThumbnailLarge => "サムネ大",
        UiTextKey::Detail => "詳細",
        UiTextKey::Sort => "ソート",
        UiTextKey::Name => "名前",
        UiTextKey::NameSortOrder => "名前のソート順",
        UiTextKey::Date => "更新日時",
        UiTextKey::Size => "サイズ",
        UiTextKey::Asc => "昇順",
        UiTextKey::Desc => "降順",
        UiTextKey::Separate => "フォルダ分離表示",
        UiTextKey::Os => "OS準拠",
        UiTextKey::Case => "Aa区別",
        UiTextKey::NoCase => "Aa無視",
        UiTextKey::Filter => "フィルタ",
        UiTextKey::Extension => "拡張子",
        UiTextKey::Url => "URL",
        UiTextKey::OpenUrl => "URLを開く",
        UiTextKey::Up => "..",
        UiTextKey::Loading => "読み込み中...",
        UiTextKey::Subfiler => "サブファイラー",
        UiTextKey::RightToLeft => "右綴じ",
        UiTextKey::LeftToRight => "左綴じ",
        UiTextKey::FolderArchive => "フォルダ / アーカイブ",
        UiTextKey::Black => "黒",
        UiTextKey::Gray => "グレー",
        UiTextKey::Tile => "タイル",
        UiTextKey::NameLabel => "名前",
        UiTextKey::Separator => "セパレーター",
        UiTextKey::SeparatorStyle => "種類",
        UiTextKey::SeparatorColor => "色",
        UiTextKey::SeparatorPixels => "幅",
        UiTextKey::None => "なし",
        UiTextKey::Solid => "単色",
        UiTextKey::Shadow => "影",
        UiTextKey::RememberSavePath => "画像保存先を記憶",
        UiTextKey::Help => "ヘルプ",
        UiTextKey::Apply => "適用",
        UiTextKey::Undo => "元に戻す",
        UiTextKey::Reset => "初期化",
        UiTextKey::Enable => "有効",
        UiTextKey::SearchPath => "検索パス",
        UiTextKey::Browse => "参照...",
        UiTextKey::LoadModules => "モジュールを読み込む",
        UiTextKey::Modules => "モジュール数",
        UiTextKey::SearchPathOsApi => "検索パス: OS API",
        UiTextKey::FitWidth => "幅に合わせる",
        UiTextKey::FitHeight => "高さに合わせる",
        UiTextKey::FitScreen => "画面に合わせる",
        UiTextKey::FitScreenIncludeSmaller => "画面に合わせる（小さい画像も拡大）",
        UiTextKey::FitScreenOnlySmaller => "小さい画像だけ画面に合わせる",
        UiTextKey::Nearest => "ニアレスト",
        UiTextKey::Bilinear => "バイリニア",
        UiTextKey::Bicubic => "バイキュービック",
        UiTextKey::Lanczos3 => "Lanczos3",
        UiTextKey::FastGpu => "高速(GPU)",
        UiTextKey::PreciseCpu => "精密(CPU)",
        UiTextKey::Stop => "停止",
        UiTextKey::Loop => "ループ",
        UiTextKey::Recursive => "再帰",
        UiTextKey::RegisteredFileAssociations => "拡張子を登録しました",
        UiTextKey::FailedFileAssociations => "拡張子の登録に失敗しました",
        UiTextKey::CleanedSystemIntegration => "システム登録を削除しました",
        UiTextKey::Workaround => "ワークアラウンド",
        UiTextKey::Archive => "アーカイブ",
        UiTextKey::ThresholdMb => "閾値 (MB)",
        UiTextKey::LocalCache => "ローカルキャッシュ",
        UiTextKey::ThumbnailSuppression => "重いサムネイルを抑制",
        UiTextKey::RestartRecommended => "再起動を推奨",
        UiTextKey::RestartToApplyPluginChanges => {
            "プラグイン設定を完全に反映するにはアプリの再起動が必要です。"
        }
        UiTextKey::PaneSide => "ペイン位置",
        UiTextKey::Left => "左",
        UiTextKey::Right => "右",
        UiTextKey::ProgramName => "プログラム名",
        UiTextKey::Version => "バージョン",
        UiTextKey::Author => "作者",
        UiTextKey::Copyright => "著作権",
        UiTextKey::ReplaceDefaultKeyBindings => "デフォルトキーバインドを置き換える",
        UiTextKey::InputBeginnerModeHelp => "かんたん設定: 1行ずつキーバインドを編集します。",
        UiTextKey::InputKeyboardOnlyNotice => {
            "現在はキーボード/マウス割り当てに対応。タブレットは今後対応予定です。"
        }
        UiTextKey::AddBinding => "割り当てを追加",
        UiTextKey::LoadCurrentCustomBindings => "現在有効な割り当てを読み込む",
        UiTextKey::ResetToDefaultBindings => "デフォルトに戻す",
        UiTextKey::FunctionLabel => "ファンクション",
        UiTextKey::KeyCaptureLabel => "キー",
        UiTextKey::PressKeyToAssign => {
            "キー欄をクリックして、割り当てたいキー/マウス入力を行ってください"
        }
        UiTextKey::CustomBindingsCount => "割り当て数",
        UiTextKey::DuplicateBindingWarning => {
            "重複する割り当ては統合されました。同一キー+修飾キーは最後の行が優先されます。"
        }
        UiTextKey::Remove => "削除",
        UiTextKey::CtrlLabel => {
            if cfg!(target_os = "macos") {
                "COMMAND"
            } else {
                "CTRL"
            }
        }
        UiTextKey::ShiftLabel => "SHIFT",
        UiTextKey::AltLabel => {
            if cfg!(target_os = "macos") {
                "OPTION"
            } else {
                "ALT"
            }
        }
        UiTextKey::MenuFileSection => "ファイル",
        UiTextKey::MenuImageSection => "画像を保存",
        UiTextKey::MenuViewSection => "表示",
        UiTextKey::MenuInfoSection => "情報",
        UiTextKey::MenuAboutSection => "このプログラムについて",
        UiTextKey::MoveItem => "移動",
        UiTextKey::CopyItem => "コピー",
        UiTextKey::DeleteItem => "削除",
        UiTextKey::RenameItem => "名前変更",
        UiTextKey::ImageInformation => "画像の情報",
        UiTextKey::ZoomInAction => "拡大",
        UiTextKey::ZoomOutAction => "縮小",
        UiTextKey::ZoomResetAction => "ズームを初期化",
        UiTextKey::ZoomToggleAction => "表示倍率を切替",
        UiTextKey::ZoomPresetAction => "倍率を指定",
        UiTextKey::OriginalSizeAction => "原寸大",
        UiTextKey::ReloadAction => "現在を再読み込み",
        UiTextKey::NextImageAction => "次の画像",
        UiTextKey::PreviousImageAction => "前の画像",
        UiTextKey::FirstImageAction => "先頭画像",
        UiTextKey::LastImageAction => "末尾画像",
        UiTextKey::ToggleAnimationAction => "アニメーション切替",
        UiTextKey::ToggleGrayscaleAction => "グレースケール切替",
        UiTextKey::ToggleSubfilerAction => "サブファイラーを切替",
        UiTextKey::MoveFileAction => "ファイルを移動",
        UiTextKey::CopyFileAction => "ファイルをコピー",
        UiTextKey::DeleteFileAction => "ファイルを削除",
        UiTextKey::RenameFileAction => "ファイル名を変更",
        UiTextKey::SetMoveFolder1Action => "移動先をFolder1に切替",
        UiTextKey::SetMoveFolder2Action => "移動先をFolder2に切替",
        UiTextKey::SetCopyFolder1Action => "コピー先をFolder1に切替",
        UiTextKey::SetCopyFolder2Action => "コピー先をFolder2に切替",
        UiTextKey::ReservedKeyWarning => "予約済み（変更できません）",
        UiTextKey::FileActionTarget => "対象",
        UiTextKey::DeleteWithTrashWarning => {
            "可能ならゴミ箱へ移動します。失敗した場合は完全に削除します。"
        }
        UiTextKey::DeleteConfirmQuestion => "よろしいですか？",
        UiTextKey::RenameExtensionFixed => "拡張子は変更できません。",
        UiTextKey::UnsupportedFilesystemAction => "未対応のファイル操作です",
        UiTextKey::FileActionDefaults => "ファイル操作の既定値",
        UiTextKey::MoveDestinationFolders => "移動先フォルダ (Folder1 / Folder2)",
        UiTextKey::MoveFolder1 => "移動先 Folder1",
        UiTextKey::MoveFolder2 => "移動先 Folder2",
        UiTextKey::UseAsMove => "移動先に使う",
        UiTextKey::ActiveMoveFolder => "現在の移動先",
        UiTextKey::CopyDestinationFolders => "コピー先フォルダ (Folder1 / Folder2)",
        UiTextKey::CopyFolder1 => "コピー先 Folder1",
        UiTextKey::CopyFolder2 => "コピー先 Folder2",
        UiTextKey::UseAsCopy => "コピー先に使う",
        UiTextKey::ActiveCopyFolder => "現在のコピー先",
        UiTextKey::Folder1 => "Folder1",
        UiTextKey::Folder2 => "Folder2",
        UiTextKey::AlertTitle => "アラート",
        UiTextKey::DestinationPathEmpty => "移動先/コピー先のパスが空です",
        UiTextKey::RenameTargetEmpty => "変更後の名前が空です",
        UiTextKey::CurrentTargetNotEditableFile => "現在の対象は編集可能なファイルではありません",
        UiTextKey::RenderWorkerDisconnected => "描画ワーカーとの接続が切断されました",
    }
}

#[cfg(test)]
#[path = "../../../tests/support/src/configs/resourses/text_tests.rs"]
mod tests;
